### ISSUE TITLE
Callback for when all local changes have been applied on server

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#131]
```
myRecord.set('A', 0)
myRecord.set('B', 0)
myRecord.whenSynced(function() {
  // All operations before `whenSynced` has been applied on the server.
})
myRecord.set('C', 0)
```

**Comment by yasserf** [comment]
When you say synced, do you mean persisted in a DB or sent to others users?

**Comment by ronag** [comment]
@yasserf: Persisted.

**Comment by ronag** [comment]
I would at least like to know that a change has successfully arrived and been applied on the deep stream server.

**Comment by yasserf** [comment]
The way deepstream works is by assuming that record updates have been applied successfully, and if they haven't you'll then recieve an error event. This is required since without it we would lose quite a bit of time sending write acks back after the data is persisted, which in a distributed system could mean a huge amount of extra time.

Deepstream also puts all the client updates in a queue, so they will process in the same order deepstream received them in. Can you provide a usecase when you need to get told if deepstream has put it in the cache?

**Comment by ronag** [comment]
@yasserf: I guess my main problem is that in some parts of my application I need to use deep stream as a database with proper transactions. I could simply write to RethinkDB but it would be nice if I only needed a single interface.

**Comment by yasserf** [comment]
@ronag: We are thinking about implementing transactions in the future, but it's quite a large task since if done incorrectly can introduce a performance bottleneck.

What you can do for now is use an RPC, meaning you don't need to use a rethinkDB driver in your frontend application.

**Comment by ronag** [comment]
@yasserf: I wouldn't mind if it has slow performance to begin with as long as it's an opt in thing. Going with RPC for now...
