### ISSUE TITLE
What happens during disconnection?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#132]
e.g. are record changes lost or retried once reconnected?

**Comment by yasserf** [comment]
They are retried once reconnected. As soon as the connection comes back up all changes you made are sent to the server, including reads, writes and pretty much anything that you done while offline.

If noone else touched the records you won't have any issues, otherwise you'll get a few merge conflicts.

A nice task we might look at during offline first would be actually merging all changes in one record into a singular update before being sent off to server, to reduce merge conflict callbacks you may receive.

Same things applies for everything else, such as events. They are buffered until the connection comes back up.

**Comment by ronag** [comment]
Maybe add to documentation?
