### ISSUE TITLE
whenReady should provide error on ACK_TIMEOUT or RESPONSE_TIMEOUT

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#148]
After `RESPONSE_TIMEOUT` or `ACK_TIMEOUT` I don't think `whenReady` can complete. Shouldn't it be called with an error in that case? Otherwise it can be "stuck" forever.

We've ended up with the following to work around this issue:

```javascript
function whenReady() {
    return new Promise((resolve, reject) => {
      const cb = (err) => {
        record.removeEventListener(cb)
        if (err)  {
          reject(err)
        } else {
          resolve()
        }
      }
      record.on('error', err => cb(err))
      record.whenReady(() => cb(null))
    })
}
```

**Comment by yasserf** [comment]
the ack timeout means that the server has not been able to process the message in time, however if it failed due to a cache or storage layer issue this will trigger a storage error as well, which means something critical occured.

In other words, the acktimeout functionality is in order to allow the developer to decide if they would like to wait for the response longer and update ui accordingly or react in any other way. It does not however mean an error occurred and hence we can't call whenReady with an error.

**Comment by ronag** [comment]
@yasserf: I still think there should be some form of timeout on `whenReady` or you risk causing deadlocks unless you know exactly what you are doing.

**Comment by yasserf** [comment]
Closing this issue since we won't be implementing error within the callback.
