### ISSUE TITLE
Don't store password as clear text in client state

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#153]
I'm a bit unsure about the authParams being stored as clear text in the client. If I login to our system using deepstream and then leave my computer for 5 min. My colleagues (as an example) could easily go to my computer open Chrome Dev Tools and read my password in clear text...

**Comment by WolframHempel** [comment]
I understand your concern: The reason we store authentication data is that whenever the connection drops and the client has to reconnect, we treat the new connection as unknown and ask it to authenticate again - so the client needs to be able to send its authentication data once more. We could encrypt/hash it etc but the problem there is, that auth-data doesn't follow any schema.

```javascript
{
 username: "Wolfram",
 password: "sesame"
}
``` 

is as valid as

```javascript
{
   token: "djgf54l40fg34j5"
}
```

or any other combination of cleartext and encrypted values. You could however easily hash the password on the clientside and send the hash to the server, rather than the password

**Comment by ronag** [comment]
Well, honestly. I am not entirely comfortable with even storing the hash like this. Though I have no better suggestion right now.

**Comment by ronag** [comment]
I feel this is medium critical. Could the server use jwt to encrypt the authParams?

**Comment by Iiridayn** [comment]
What we had planned in our project was the client gets a token which it uses for subsequent authentication requests, permitting the client to immediately discard the username and password. We also had planned session timeouts though, permitting us to expire tokens (requiring re-entering authentication credentials), not sure if that would work for deepstreamIO as a general solution as without a timeout the token storage leaks memory.

Might use some kind of capability token - encrypt timestamp+auth using symmetric encryption on the server, return that as the token w/a HMAC - the timestamp can expire tokens without having to store them. Problem then would be managing the encryption key between server restarts/across a cluster.

**Comment by yasserf** [comment]
I don't think this is an issue anymore because the way almost all authentication happens in deepstream is via the webhook api.

The authToken is read off a cookie from the websocket, validates against it and then does permissioning. So people actually just login using `.login()` to authenticate correctly. 

I'm keeping this open though because it might be useful to have deepstream return a cookie which replaces the auth parameters in the SDK. It's easy enough to implement

**Comment by yasserf** [comment]
Closing as we won't be getting around to doing this.
