### ISSUE TITLE
Does subscribe increase record reference count?

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#173]
e.g. given the following code

```javascript
const rec1 = ds.record.getRecord(recordName)
assert(rec1.usages === 1)
rec1.subscribe(cb)
rec.discard()
assert(rec1.usages === 1) // ??? or is it === 0
rec.unsubscribe(cb)
```

What is the expected behaviour? Should/Will I still receive updates after the call to `discard`?

**Comment by yasserf** [comment]
it would be 0, you will not recieve updates since an unsubscribe would be send to the server.

However this should also destroy the record, meaning you are holding a reference to a dead object which will not get updates again in the future.

You can listen to a `discard` event which means the record has been deleted remotely or locally and will no longer received updates,
