### ISSUE TITLE
get after set while !isReady

### ISSUE THREAD

**Issue by ronag** [deepstreamIO/deepstream.io-client-js#174]
I think I posted this issue before but I can't find it anymore.

Given that we now have merge strategies I see no reason at all for get waiting until `set` to see local changes.

i.e.

Currently:
```javascript
const rec = ds.record.getRecord(recordName)
rec.set({ name: 'foo' })
console.log(rec.get()) // {}
rec.whenReady(() => console.log(rec.get()) // { name: 'foo' }
```
Suggested:
```javascript
const rec = ds.record.getRecord(recordName)
rec.set({ name: 'foo' })
console.log(rec.get()) // { name: 'foo' }
rec.whenReady(() => console.log(rec.get()) // { name: 'foo' }
```

I don't believe this should be a problem with the current implementation? i.e. isn't it enough to just remove the pending write queue on the client?

**Comment by yasserf** [comment]
Interesting. We currently have enough things for 1.0.3/1.0.2 so will get back to this during next sprint.

**Comment by yasserf** [comment]
Would you also expect this functionality on a patch basis? I recalled issues that might arise from that but not entirely sure what tbh, other than the fact there wouldn't be much point in storing all the individual updates when u come back online and instead just send the current state ( with the correct version number ).

This is expected behaviour for offline first behaviour, but we won't be picking this up for this/very near future release. We need to start looking into listening as well as a couple of features in the backend + polishing off the native java client and setting porting e2e tests. Generally have our hands full for the next month! =D

**Comment by yasserf** [comment]
Closing as this is now references as AC for Offline mode epic
