### ISSUE TITLE
Promises API

### ISSUE THREAD

**Issue by gothy** [deepstreamIO/deepstream.io-client-js#22]
Please consider making an alternative(new?) promise-based API that could be easier to wrap head around and use with upcoming(supported in Babel already) async\await.

It would be great to use deepstream basic get\set APIs this way in future:

```js
try {
  const record = ds.record.getRecord( 'someUser' );
  const recordData = await record.get();
  // do smth with data...
  record.set({new: 'data'});
} catch(err) {
  console.log(err); // getting or setting failed
}
```

**Comment by yasserf** [comment]
Hello,

Thanks for the suggestion. We unfortunately don't have any bandwidth

**Comment by gothy** [comment]
I'm not sure I got the 'bandwidth' thing :)

**Comment by yasserf** [comment]
Hey, thanks for suggestion. We have other a few features with higher priority in the upcoming months but would love if someone can take a look at this if they have time!

Yeah, sorry about the initial comment, hit enter halfway by accident.

**Comment by gothy** [comment]
Ah, OK :)

**Comment by yasserf** [comment]
Quick update...

Retrofitting promises/es6 features into the current client would be quite a huge amount of work and slow down the current client in some situations. My guess for the solution to this issue is to maintain a separate client written from the ground up with that approach in mind.

That unfortunately won't be something we will be doing anytime soon since we are focused on looking at adding features into deepstream to cater for resilience which will benefit current clients and be integrated into the spec.

We are in the process of adding a cucumber test suite to allow different clients to be written quickly with a scaffold for all the client/server messages. It should really speed up development by having acceptance tests already written.

If anyone would like to take a look at this feel free to let us know and we'll love to collaborate!
