### ISSUE TITLE
event.once eventemitter equivalent

### ISSUE THREAD

**Issue by srossross** [deepstreamIO/deepstream.io-client-js#288]
Is there a pattern in deepstream for an event to only be handled once? 

For example, if I have a comment system where I have `comment {body: str, upvotes: int, score: float}` I want the user to be able to upvote but not be able to modify the score. When a client upvotes I would like to emit an event `client.event.emit('comments/compute-score', recordName)` that will be handled exactly one time. 

Maybe I am thinking about the problem wrong.

**Comment by WolframHempel** [comment]
Hi @srossross,

oh dear, I've got a bit carried away with that answer - so much so that I started adding headlines to break it down :-). TL;DR; version: use records and rpcs

## Long version:
I'm afraid there isn't an "only once event", however you could unsubscribe from an event channel after receiving the event. deepstream is first and foremost about records/stateful data though - and gives you the tools you need to work with it. Here's one possible solution using records and rpcs:

## Requirements

Just to be sure I understand all aspects of what you're looking for:

As a user upvotes a comment, you'd want to:

- ensure that the user hasn't upvoted the comment before
- ensure that the upvote is increased by exactly one
- calculate the new score, e.g. based on upvotes/time

I assume the calculation of the new score would need to happen on the server side as the client won't be trusted to do this, right?

## Approach

Given your record is structured as

```javascript
{
    body: 'some comment',
    // keeping a list of upvoters to ensure
    // everyone uploads only once
    upvoters: [ 'userA', 'userB' ],
    upvotes: 2,
    score: 0.56
}
```

you could now register a remote procedure call (RPC) from a provider that runs on the backend, e.g. a node or java process:

```javascript
ds.rpc.provide( 'upvote-comment', data, response => {
    // data would be a map with the following fields
    // {
    //   username: 'userC',
    //   commentId: 'comment/345j3lj4lj5'
    // }
    ds.record.getRecord( data.commentId ).whenReady( record => {
        // get the raw-data from the comment record
        var comment = record.get();
        // add the username to the array of upvoters
        comment.upvoters.push( data.username );
        // increase the upvotes by one
        comment.upvotes++;
        // run your score algorithm
        comment.score = /* your score formula */;
        // save the data to the record
        record.set( comment );
        // let the server know we're no longer interested
        // in updates for this record
        record.discard();
        // let the user know it worked
        response.send();
    });
});
```

## Valve

Everything else we'll do in [Valve](https://deepstream.io/tutorials/core/permission-conf-simple/), deepstream's permission and rule language. We'll use it to make sure that
- the user hasn't already upvoted that comment
- the username provided in the RPC data above is infact the username that user is logged in as

The resulting Valve rule would look as follows

```yaml
rpc:
  upvote-comment:
    request: "_(data.commentId) && _(data.commentId).upvoters.indexOf(user.id)=== -1 && data.username === user.id"
```

The above also ensures that the comment references in `commentId` actually exists.

You would also need to ensure that only your backend process can provide the `upvote-comment` rpc and that only it can change the `upvoters`, `upvote` and `score` fields of the comment as well as that only the original poster could change its `body`, but I've omitted that bit for brevities sake.

## On the client
And that's it. On the client the user could now subscribe to the comment record

```javascript
var comment = ds.record.getRecord( 'comment/345j3lj4lj5' );
comment.subscribe( 'upvotes', updateUpvotes );// etc...
```

upvote it via

```javascript
ds.rpc.make( 'upvote-comment', {
    username: 'userC',
    commentId: 'comment/345j3lj4lj5'
}, (err, result ) => {})
```

and she as well as all other users would immediatly see the score and upvote count change

**Comment by srossross** [comment]
Thanks @WolframHempel, this answers my question. I will try and post a concise open source example once I have a better understanding of deepstream.

I have some follow on questions. 
1. Would I want to set the valve permissions of a comment so that a user can not set the score? eg
    ```
    record:
        comment/$commentId:
            write: "data.score === undefined && ..."
    ```
1. What would be the best way to maintain a sorted list of comments? should I use a `List` or an `RPC` again?
    1. If I am using the mongodb storage layer, is it bad practice to query mongodb for the records directly so I can  sorted and/or limit a list of comments in an RPC call?

**Comment by WolframHempel** [comment]
1) Yup, absolutely. Syntax would be a little bit different though. Valve exposes two objects: `data` the **complete** data the record would have after the change and `oldData`, the current data of the record. To make sure a field is unchanged you'd compare the two, e.g.

```yaml
write: "data.score === oldData.score" 
```

2) For some databases, e.g. RethinkDB deepstream has search providers. For Mongo I'd suggest using [listening](https://deepstream.io/tutorials/core/datasync-records/#listening) which lets you know about the records/lists/events other clients are interested in. Basically you'd listen from within your backend service and populate list contents for lists containing search params as people subscribe to them. E.g. when a client runs

```javascript
myList = ds.record.getList( 'comments/article324?sort=desc')
```

the following would be invoked on the server
```javascript
ds.record.listen( 'comments/.*', (match, isSubscribed, response) => {
	response.accept()

	if( isSubscribed ) {
		//pseudo code
		var searchParams = url.parse( match );

		mongoDb.query( searchParams, ( result ) => {
			// assuming result is an array of record ids, e.g.
			// [ 'comment/dfhs', 'comment/sdaf' ]
			var list = ds.record.getList( match );
			list.setEntries( result )

			// Here we unsubscribe from the list immediatly. 
			// If you want to provide more realtimy updates,
			// e.g. via polling or trailing MongoDB's oplog you could also keep the
			// list and call setEntries / addEntry / removeEntry periodically
			list.discard()
		})
	} else {
		// no one interested in this list anymore
		ds.record.getList( match ).delete()
	}
})
```

**Comment by srossross** [comment]
Thanks again. 

It seems to me that as my scope grows, I will need a lot of rpc endpoints for a larger project. Would you recommend using deepstream for these RPCs - or should I create a restful or other service that would be a companion to deepstream?

**Comment by yasserf** [comment]
deepstream can easily support lots of RPC endpoints so there isn't a need to use a seperate restful API or service

**Comment by yasserf** [comment]
@srossross closing this issue, feel free to reopen if anythings missing
