### ISSUE TITLE
Best way to add to or remove from an array in a record?

### ISSUE THREAD

**Issue by rsdrsd** [deepstreamIO/deepstream.io-client-js#323]
I am doing the following to add to an array in a record:
```
let users = record.get('users') || [];
if (users.indexOf(userName) < 0) {
  users.push(userName);
  record.set('users', users);
} 
```
I am doing the following to remove from an array in a record:
```
let users = record.get('users') || [];
let index = users.indexOf(userName);
if (index > -1) {
  record.set('users[' + index + ']', undefined);
} 
```
Is this good practice and how about data consistency? Can the array be updated by some other process between get and set of the array? Can data be lost? Or should all these manipulations run in the same backend client process?

**Comment by yasserf** [comment]
hey @rsdrsd,

Sorry for the late reply. Lists follow the same rules as records, which means that they follow a version number and if for any reason that version number becomes out of sync you will then have the chance to apply your changes ontop of the actual remote value. Merge conflicts don't happen that often due to the speed of the change, but you won't lose any data at any time. You can also run the data in the multiple backend processes, but just keep in mind if it is a heavy traffic field updated in a distributed fashion you will be greatly increasing the odds of a write conflict occurring!

Hope that helps!
