### ISSUE TITLE
Be able to pause and resume websocket connections at will

### ISSUE THREAD

**Issue by ScreamZ** [deepstreamIO/deepstream.io-client-js#366]
Hello,

I really enjoy working with deepstream. But I can't figure out a proper way to deal with my case.

## Context

I'm building a Ionic2 (cordova) application that work with one host and multiple clients. 

**The host** is sending questions to clients which subscribe to it and the clients have a loader while no question are displayed. When a new question is received, an interface appears and they can answer the question. Then the loader come back and wait until the host decides to dispatch next question.

## Issue

The thing is that people might go on another application like Facebook (or something like) between questions, which result of the Android (or IOS) application pause (in background). 

There I want to do one of two things: 

* Stay connected to keep receiving subscriptions and probably dispatch a local notification upon new question. (My preferred choice). It may depends on system limitation and store compliance.
* Let the socket expire, and listen for the "resume" event of Cordova in order to reconnect the user and restore subscription. (Which looks like the easier one)

My question is, do you have a good practice to achieve that goal ? Or what is the system behavior on the second case ? Subscription are still valid ? I'll receive new events ? Current record value ?

Here is my code 
```JS
this.platform.resume.subscribe(() => {
      const CONNECTION_STATE = deepstream.CONSTANTS.CONNECTION_STATE;
      if (this.ds.getConnectionState() === CONNECTION_STATE['OPEN']) return;
      if (this.ds.getConnectionState() !== CONNECTION_STATE['CLOSED']) this.ds.close();
      this.ds.login(null);
    })
```
Thanks for reading me,
Best regards

**Comment by yasserf** [comment]
Hello!

Great question! I'm not exactly experience with cordova, but my guess is the operating system will throttle down/cut off network to background tabs. If that is the case the server will most likely kill the connection since it isn't responsive heartbeat events.

So recommended suggestion? We are looking at add a `pause` and `resume` event on the server that allows the connection to be voluntarily closed. However, given that currently isn't there, option two should also work fine. The client will resubscribe to all the events/records/rpcs and also flush all pending events.

However, the catch here is that you can't create a new client, but would rather need to wait for the sdk to reconnect automatically.

I'll repurpose this card as a connection lifecycle issue and hopefully get this feature in the next release, its a quick win!

**Comment by yasserf** [comment]
@AlexBHarley @jdmnd Makes sense this gets duplicated in both the Java/swift and c++ sdks!

**Comment by ScreamZ** [comment]
All right, feel free to ping me ;) I'll keep using my snippet then.

Regards

**Comment by yasserf** [comment]
Resume and pause was added, bit late but better than never right?  😅

**Comment by ScreamZ** [comment]
Nice one ;) you're right.

I was very happy to use deepstream but everything stopped suddenly. Has the company been bankrupt ? I didn't saw any informations about the future and how can we still be confident in creating new project using it ? Is community maintaining the project ?

Thanks :)

**Comment by yasserf** [comment]
hey! It's a little complicated tbh, I'll be releasing an independent blog post at some point explaining where we are. Gist is the platform didn't work out and we haven't managed to raise a series A. After that there was a year of maintenance/enterprise support while I was trying to figure out what to do / recovering from the insane 3 year mental and physical taxation.

For now though I am extremely happy to say that I found a part-time remote job for a company that uses deepstream and who are happy for me to put all the features I add into the core back into OS (part time since not all work is related to them). We already have a roadmap and you can see the new (similar branding!) website deepstream.io back fully in OS.

I get it will be hard to get people to reuse deepstream given the decisions that effected trust that we took trying to survive as a tiny fish in a big sea. But my choices are no longer backed by profit/loss sheets and I really just want to see people understand how to shape realtime-systems in a way that makes sense, regardless of whether it uses deepstream as a stepping stone to a bigger system or in an ideal world where the technology scales with them.

**Comment by ScreamZ** [comment]
Wonderful, see you soon then :) Thanks for the quick reply 👍
