### ISSUE TITLE
Multiple setData on the same record will only fire the callback once

### ISSUE THREAD

**Issue by SejH** [deepstreamIO/deepstream.io-client-js#395]
Using deepstream.io-client-js 2.2.1 and deepstream.io 3.0.0, running the following code will result in the following output.
``` javascript
const dsc = require('deepstream.io-client-js')('ws://localhost:8000');

function setData(i) {
  console.log('Set Data!');
  dsc.record.setData('user/testRecord', { foo: i }, error => {
    console.log('Set Data Callback', error);
  });
}

dsc.login(() => {
  for (let i = 0; i < 5; i++) {
    setData(i);
  }
});

```

Output:
```
Set Data!
Set Data!
Set Data!
Set Data!
Set Data!
Set Data Callback null
```

I believe that the issue lies [here](https://github.com/deepstreamIO/deepstream.io-client-js/blob/731d3eb9a912fda2c03ca74ea1462f2b9e354fa2/src/record/record-handler.js#L301) where the callbacks are cleared.

**Comment by yasserf** [comment]
Hey! We were just discussing this today via lunch. We are considering adding correlationIds to the acks in order to ensure their uniqueness. 

Would you mind me asking what your use case is?

**Comment by daviderenger** [comment]
One example, updating multiple values on the same record: (note that we have wrapped setData calls in promises)

  deepstreamClient.rpc.provide('setting:user:setScale', (data, response) => {
    response.autoAck = false;

    if (typeof data.desktop !== 'number' || typeof data.mobile !== 'number') {
      return response.error(typeof data.desktop);
    }

    const desktop = Math.max(75, Math.min(150, data.desktop));
    const mobile = Math.max(75, Math.min(150, data.mobile));

    return Promise.all([
        dsUtils.record.setData(`userAdmin/${data.userId}`,'scaleDesktop', desktop),
        dsUtils.record.setData(`userAdmin/${data.userId}`,'scaleMobile', mobile)
      ])
      .then(() => {
        response.send();
      })
      .catch(error => {
        logger.error({ filename: __filename, RPC: 'setting:user:setScale' }, error);
        return response.error();
      });
  });

A call to this RPC will always result in ACK_TIMEOUT on the client calling it.

Another use case is two clients calling RPCs at almost the same time.

Anyway, this happens for us pretty often and if its not solved we will probably have to write some own logic in the client collecting all callbacks and call them all on the response callback from deepstream server.

By the way, setData is a life saver for us since we do a lot of:
getRecord
then set something
then discard

on our servers and we are constantly fighting UNSOLICITED_MESSAGE errors.

**Comment by yasserf** [comment]
Fixed in V4. Really sorry for the terrible turnaround time =(
