### ISSUE TITLE
[QUESTION & BUG] Supported platforms? (issues with Safari 9.2)

### ISSUE THREAD

**Issue by Kitanotori** [deepstreamIO/deepstream.io-client-js#396]
Couldn't find any information on the supported platforms. I am having serious issues with older Safari versions. No error shown, but Deepstream doesn't start at all. Tried with several 2.x.x versions of Deepstream JavaScript client. Also some Android users (browser, not native) reported issues with my Deepstream-based app, but haven't yet been able to confirm.

Using the code from https://cdnjs.com/libraries/deepstream.io-client-js

e.g. `<script src="https://cdnjs.cloudflare.com/ajax/libs/deepstream.io-client-js/2.2.1/deepstream.min.js"><script>`

**Comment by mrby** [comment]
testing:

browser used | deepstream problem? | dashboard problem?
safari 4 | yes | yes

**Comment by mrby** [comment]
after testing further with murilo:
- some issue with using the test page for testing RPCs  is that it uses `console.time…`.  some browsers throw an error, as `console` does not have `time` (for some browsers).
- when trying to create a client, the error `object does not support this action` is triggered.
- some issues with connecting in IE are because of a security issue that rejects connecting with `localhost` but accepts `127.0.0.1`

**Comment by yasserf** [comment]
hey @Kitanotori,

Apologies for the late reply. We don't use any new features but on doing a bit of investigation noticed a few keywords like delete in older IE version don't work.

We will be making sure the next release works down to IE8, we have quite a few people who built mobile browser apps using deepstream but would be more than happy to fix whatever issues you find.

Cheers,
Yasser

**Comment by mrby** [comment]
currently writing a script to check everything on our test-page.
