### ISSUE TITLE
Presence.unsubscribe will cause crash if presence.subscribe was called more than once

### ISSUE THREAD

**Issue by TimMun** [deepstreamIO/deepstream.io-client-js#510]
If `dsClient.presence.subscribe(username, onPresenceChange)` is called twice, the subsequent unsubscribe call will cause "invalid argument: "user" or "callback" error".

`@deepstream/client/dist/presence/presence-handler.js:95
        throw new Error('invalid argument: "user" or "callback"');
              ^
Error: invalid argument: "user" or "callback"`

This scenario may happen when a user logs in with the same username from two different devices. (In my case, I do a presence.subscribe when the user logs in, specifically in the POST request handler of the http auth server. I'm still digging into why this happens, but the auth server seems to be pinged twice, causing the double presence subscribe.)

A repo to reproduce the bug is here: https://github.com/TimMun/deepstream-rpc-bug

**Comment by yasserf** [comment]
This isn’t really a bug, if anything we might need to just an api to stop your from subscribing more than once. 

Unsubscribe is backed by an emitter, unsubscribing with a name and the same callback removes all callbacks in first call, so doing so twice means the callback wasn’t subscribed on the second call. 

I’ll look into why it’s throwing an error instead of being quiet though. Thank you for the repo!
