### ISSUE TITLE
`DeepstreamClient is not defined` when using tutorial code

### ISSUE THREAD

**Issue by chris-aeviator** [deepstreamIO/deepstream.io-client-js#511]
Hi, I'm keen on trying deepstream, but your tutorial code

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.deepstream.io/js/client/latest/ds.min.js"></script>
  </head>
  <body>
    <input type="text" />
    <script type="text/javascript">
      const client = new DeepstreamClient('localhost:6020')
      client.login()
    </script>
  </body>
</html>

```

returns a `ReferenceError: DeepstreamClient is not defined` 

EDIT:

before the question arrises, `ds.js` is correctly pulled

![image](https://user-images.githubusercontent.com/11522213/67660800-30c0e480-f992-11e9-86bc-cbf925ec5c85.png)

**Comment by chris-aeviator** [comment]
Seems to me the answer is `var client = new deepstream.DeepstreamClient()`

**Comment by yasserf** [comment]
Hey thanks for raising! Will look into this, seems like bundler is adding an extra namespace ontop

**Comment by kotaries** [comment]
Hello. Looks like your CDN is down. The link doesn't work, so I can't even start learning tutorials. Any suggestions please?

**Comment by yasserf** [comment]
Use npm install instead

**Comment by yasserf** [comment]
Actually ended up creating another CDN in my own aws account to continue this working. Sorry about the change, we removed all the assets from the deepstreamHub account, but since most of the builds expect an S3 bucket I ended up creating another. It should be up and running again.

But generally speaking I would recommend using npm as the cdn versions I provide are not versioned and always latest.
