### ISSUE TITLE
Can't subscribe to a record with record.subscribe(callback) with callback being the only param because of Typescript definitions.

### ISSUE THREAD

**Issue by zoltangbereczky** [deepstreamIO/deepstream.io-client-js#545]
According to the documentation ``` record.subscribe ``` should be able to take only the callback as a param for listening to any changes on the record. However, the current typing doesn't allow that. 

I'd be happy to send a PR, but since normalizeArguments makes it possible to rearrange the order of the params as well, I'm not entirely sure how to approach this without a breaking change or without nasty TS workarounds.

```
// from src/record/record.ts

public subscribe (path: string, callback: (data: any) => void, triggerNow?: boolean) {
        const parameters = utils.normalizeArguments(arguments)
        this.subscriptions.push(parameters)
        this.record.subscribe(parameters, this)
    }
```

**Comment by jaime-ez** [comment]
Hi, I'm not using TS on my apps so I haven't encountered this issue, would setting path as optional work :
`public subscribe (path?: string, callback: (data: any) => void, triggerNow?: boolean) {` ?

Another option would be to set path type as `string | null` and then when subscribing to the complete record you pass `null` as path (that works currently)

**Comment by zoltangbereczky** [comment]
Hi,

I'd personally go with the second solution. However, that would be a breaking change. 
Setting the path to optional won't work because a required parameter cannot follow an optional parameter.

So the question remains, is it ok to introduce a breaking change to the client? 😊
If yes, I'll create a PR.

**Comment by jaime-ez** [comment]
Let me recap and see if we are talking about the same:

1. The TS compiler throws error when you do `record.subscribe(callback)` due to typing issues, it requires a defined path with a string value (I haven't veryfied this, but seems legit from the source)
2. In the current client you can subscribe to the complete record by doing `record.subscribe(callback)` or `record.subscribe(null, callback)` : both options work

Possible solutions:

1. Set the path type to `string | null` and thus TS users would have to call the function as `record.subscribe(null, callback)` for subscribing to the complete record and wouldn't have type problems from the TS compiler. As far as I see this won't be a breaking change for JS  users, although a nasty difference between TS and JS usage.

2. Follow my linter suggestion :) Set the `record.subscribe` function parameters as unused by prefixing an underscore: `_path, _callback, _triggerNow` : could you check if this solves your issue?

**Comment by zoltangbereczky** [comment]
Yes, it seems that we are on the same page.  Thanks for the clarification.

Prefixing the params doesn't solve the issue.

I'd go with setting the path type to ```string | null```

I was talking about a breaking change because my initial thought was not to allow different usages for TS and JS users.
However, if you say that we can live with the non-consistent calls, then I would recommend updating the docs to promote the ```record.subscribe(null, callback)``` usage for everyone from now on.

**Comment by jaime-ez** [comment]
Another option, take a look at the same `record.ts` source [here for example](https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/record/record.ts#L57) : multiple definitions are used in order to cover all possible cases. Maybe that's the rigth way to go. Hope you have a chance to test it, that would be the ideal scenario, no changes needed to documentation or anything else.

**Comment by zoltangbereczky** [comment]
Great suggestion. 👍  Works like a charm. PR sent.

**Comment by jaime-ez** [comment]
Excelent
