### ISSUE TITLE
Deprecate old SDK

### ISSUE THREAD

**Issue by ScreamZ** [deepstreamIO/deepstream.io-client-js#594]
Hi,

Just figured out that I'm using the old SDK https://www.npmjs.com/package/deepstream.io-client-js, is there any way to deprecate this one or discard it ?

**Comment by jaime-ez** [comment]
Hi, I don't have access to that org in npm, and that sdk is still in use with the [old server implementation](https://www.npmjs.com/package/deepstream.io)

Where you using the old sdk from a long time ago? Or you downloaded it following a tutorial ? Please let me know if the documentation still has a reference to it in order to change it

**Comment by ScreamZ** [comment]
I've no idea, might be a mistake from me using auto-completion on my shell.
