### ISSUE TITLE
investigate VERSION_EXISTS for concurrent connections from the same client

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-client-js#99]

**Comment by ajperella** [comment]
Turns out this was the deepstream-react component doing this (after modification to remove global dbClient variable)

The componentWillUpdate method does a dsRecord.set even if the data has not changed.

I am sure there are better ways to check if the state has changed but for now I have just done the nasty:

componentWillUpdate: function( nextProps, nextState ) {		
		var v=this._cloneState( nextState ) ;
		//has it changed?
		if (JSON.stringify(nextState)!=JSON.stringify(v))
		{
			this.dsRecord.set( v);
		}
	},

<no shame/>

**Comment by yasserf** [comment]
Moving issue to the react deepstream repo. Good catch!
